### ISSUE TITLE
Open my VOD file and then the software crushed

### ISSUE THREAD

**Issue by inkforest** [Alycse/TwitchVodWithChatPlayer#1]
**Describe the bug**
Open my VOD file, my cursor loads for a while, then the software closes automatically.

**To Reproduce**
1. Click on open VOD
2. Click on my VOD file
3. Wait for a while

**Expected behavior**
...Just open my VOD file so I can watch
And a suggestion: It seems that it uses the Windows Media Player to play the VOD, a very bad media player IMO. I think a "start" button can be added to start to display the chat, and when the user plays an VOD he just press the button. There may be a time difference but it's quite alright to me. This function can suit the user uses various media players.

**Screenshots**
<img src="https://s2.ax1x.com/2019/08/04/e6qj2R.gif" alt="e6qj2R.gif" border="0" />

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version 1.0.0.0

**Comment by Alycse** [comment]
Hey sorry for the late reply (24 days!), didn't know GitHub doesn't notify for new issues, I'll try to fix this!
