### ISSUE TITLE
transparent background is not working 

### ISSUE THREAD

**Issue by Nutri626** [Alycse/TwitchVodWithChatPlayer#2]
Hello , transparent background is not working at all ,[ here is the example](https://imgur.com/a/L9lj1A6) of how it is , also can i make text small or something ? its minor issue but still

**Comment by Alycse** [comment]
Thanks for the report! May I ask what version you're using and what OS?

**Comment by Nutri626** [comment]
> Thanks for the report! May I ask what version you're using and what OS?

latest version (downloaded it twice so there is not mistake about that) and im using win 8.1

**Comment by Nutri626** [comment]
i just tested it on my old pc (win 7 / 32 bit) and it worked , but somehow on my new pc transparent chat box is not working , i have tried to edit code to make it transparent but then its white or grey....

**Comment by Alycse** [comment]
Sorry I didn't get to reply earlier! Anyways, I'm glad it's working now! :)
