### ISSUE TITLE
transparent dragger

### ISSUE THREAD

**Issue by Nutri626** [Alycse/TwitchVodWithChatPlayer#3]
Hello , can i totally hide this dragger button somehow ? i tried to remove it from the files but its still appearing and ruining fullscreen transparent experience , thanks

**Comment by Alycse** [comment]
Not right now unfortunately, but I'm gonna make it removable in the next update - which I'll upload shortly!

**Comment by Alycse** [comment]
I've added the option to hide the chat box dragger in the latest update (1.1.5.1). You may do this by going to the 'Chat' menu and clicking 'Hide Chat Box Dragger', or by pressing CTRL+D.
Thank you for the suggestion!
