### ISSUE TITLE
Error while downloading resources due to old API URL's

### ISSUE THREAD

**Issue by Maffia171** [Alycse/TwitchVodWithChatPlayer#7]
Hi, i'm having issues downloading BTTV/FFZ emoticons with the Download Resources option.
The download for the badges seems to work fine but BTTV Emoticons give an Error 403 Forbidden and the FFZ Emoticons give an Error 400 Bad Request. 
It seems the issue is that some API URL's have to be updated. The new BTTV API for example now uses channel_id instead of channel name.
BttvChannelEmoticonUrl: https://api.betterttv.net/3/cached/users/twitch/<channel_id>
BttvGlobalEmoticonUrl: https://api.betterttv.net/3/cached/emotes/global
The FFZ error seems to be because its querying 1000 per page when the max at the moment is 200.

**Comment by Alycse** [comment]
Ah yes, the emote apis have been updated since last release and I never got the chance to fix them. I'm gonna try to fix it right now since I have time. Thanks!

**Comment by Maffia171** [comment]
Thanks for the fast fix, emote downloading works great now!
Just found this software today and for me it's almost perfect, the only thing I had noticed is #5. Compared to opening the VOD in for example MPV the video playback in the program unfortunately doesn't look as smooth. If there is anyway you could look at that sometime that would be great.

**Comment by Alycse** [comment]
Alright, I'll try to take a look into it.
